name: burningbros_product
description: "A Flutter project for Burning Bros's home assignment"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.4
  fluro: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  pretty_dio_logger: ^1.3.1
  dio: ^5.4.2+1
  path_provider: ^2.1.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_svg: ^2.0.10+1
  flutter_html: ^3.0.0-beta.2
  collection: ^1.18.0
  responsive_sizer: ^3.3.1
  internet_connection_checker: ^1.0.0+1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.2.0
  retrofit_generator: ^8.1.0
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.1.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/image/

flutter_gen:
  output: lib/core/generated
  line_length: 80
  integrations:
    flutter_svg: true  